[build]
  command = "npm run build"
  publish = ".next"

[functions]
  included_files = ["content/**"]

[[redirects]]
  from = "https://www.michellecarter.ie/*"
  to   = "https://michellecarter.ie/:splat"
  status = 301
  force  = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
